import{a as w,S as v,i}from"./assets/vendor-BkC4bTqC.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const d of o.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&l(d)}).observe(document,{childList:!0,subtree:!0});function r(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function l(t){if(t.ep)return;t.ep=!0;const o=r(t);fetch(t.href,o)}})();const S="55096474-b1fd7eaea0590dea563cfdba0",q="https://pixabay.com/api/";async function m(a,e=1){const r={key:S,q:a,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:15};return(await w.get(q,{params:r})).data}const y=document.querySelector(".gallery"),p=document.querySelector(".loader"),h=document.querySelector(".load-more");let B=new v(".gallery a",{captionsData:"alt",captionDelay:250});function g(a){const e=a.map(r=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${r.largeImageURL}">
          <img class="gallery-image" src="${r.webformatURL}" alt="${r.tags}" />
        </a>
        <div class="info">
          <p><b>Likes:</b> ${r.likes}</p>
          <p><b>Views:</b> ${r.views}</p>
          <p><b>Comments:</b> ${r.comments}</p>
          <p><b>Downloads:</b> ${r.downloads}</p>
        </div>
      </li>`).join("");y.insertAdjacentHTML("beforeend",e),B.refresh()}function M(){y.innerHTML=""}function L(){p.classList.remove("is-hidden")}function c(){p.classList.add("is-hidden")}function b(){h.classList.remove("is-hidden")}function u(){h.classList.add("is-hidden")}let n="",s=1,f=0;const $=document.querySelector(".search-form"),O=document.querySelector(".load-more");$.addEventListener("submit",async a=>{if(a.preventDefault(),n=a.currentTarget.elements.query.value.trim(),!!n){s=1,M(),u(),L();try{const e=await m(n,s);if(c(),e.hits.length===0){i.error({message:"Sorry, there are no images matching your search query."});return}g(e.hits),f=Math.ceil(e.totalHits/15),s<f&&b()}catch{c(),i.error({message:"Something went wrong!"})}}});O.addEventListener("click",async()=>{s+=1,u(),L();try{const a=await m(n,s);c(),g(a.hits);const e=document.querySelector(".gallery-item");if(e){const{height:r}=e.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}s>=f?(u(),i.info({message:"We're sorry, but you've reached the end of search results."})):b()}catch{c(),i.error({message:"Failed to load more images."})}});
//# sourceMappingURL=index.js.map
