import{a as w,S as v,i as n}from"./assets/vendor-BkC4bTqC.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))d(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const u of o.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&d(u)}).observe(document,{childList:!0,subtree:!0});function r(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function d(t){if(t.ep)return;t.ep=!0;const o=r(t);fetch(t.href,o)}})();const S="55096474-b1fd7eaea0590dea563cfdba0",q="https://pixabay.com/api/";async function m(s,e=1){const r={key:S,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:15};return(await w.get(q,{params:r})).data}const h=document.querySelector(".gallery"),y=document.querySelector(".loader"),p=document.querySelector(".load-more");let B=new v(".gallery a",{captionsData:"alt",captionDelay:250});function g(s){const e=s.map(r=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${r.largeImageURL}">
          <img class="gallery-image" src="${r.webformatURL}" alt="${r.tags}" />
        </a>
        <div class="info">
          <p><b>Likes:</b> ${r.likes}</p>
          <p><b>Views:</b> ${r.views}</p>
          <p><b>Comments:</b> ${r.comments}</p>
          <p><b>Downloads:</b> ${r.downloads}</p>
        </div>
      </li>`).join("");h.insertAdjacentHTML("beforeend",e),B.refresh()}function M(){h.innerHTML=""}function b(){y.classList.remove("is-hidden")}function c(){y.classList.add("is-hidden")}function L(){p.classList.remove("is-hidden")}function l(){p.classList.add("is-hidden")}let i="",a=1,f=0;const $=document.querySelector(".form"),O=document.querySelector(".load-more");$.addEventListener("submit",async s=>{if(s.preventDefault(),i=s.currentTarget.elements["search-text"].value.trim(),!!i){a=1,M(),l(),b();try{const e=await m(i,a);if(c(),e.hits.length===0){n.error({message:"Sorry, there are no images matching your search query."});return}g(e.hits),f=Math.ceil(e.totalHits/15),a>=f?(l(),n.info({message:"We're sorry, but you've reached the end of search results."})):L()}catch{c(),n.error({message:"Something went wrong!"})}}});O.addEventListener("click",async()=>{a+=1,l(),b();try{const s=await m(i,a);c(),g(s.hits);const e=document.querySelector(".gallery-item");if(e){const{height:r}=e.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}a>=f?(l(),n.info({message:"We're sorry, but you've reached the end of search results."})):L()}catch{c(),n.error({message:"Failed to load more images."})}});
//# sourceMappingURL=index.js.map
